name: new_chemion_color
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  http: ^0.13.4
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  easy_localization: ^3.0.1
  flutter_ble_lib_ios_15: ^2.5.2
  connectivity_plus: ^2.3.9
  fluttertoast: ^8.1.2
  simple_gradient_text: ^1.2.4
  logger: ^1.1.0
  android_intent: ^2.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - assets/config/.env
